### PR TITLE
fix: allow any action payload if action was never typed

### LINKED ISSUE #4: Typescript error on event invocation with argument
After the last update with the improved types, I now get an error whenever I invoke an event with an argument.

```ts
state.paginate(page);
```

```sh
Error: Expected 0 arguments, but got 1. (ts)
    state.paginate(page);
```

Thanks a lot for this library, really useful!

### PR DESCRIPTION
**Pull request by ivanhofer**
closes #4

### CODE REVIEW

**Comment by ivanhofer** [comment]
With this PR it is possible to pass any type and amount of arguments as long as the action function was never typed.
As soon as the action would be `paginate(page: number)` instead of `paginate()`, this would not work.

**Comment by kenkunz** [comment]
Thanks again for the quick response and fix, @ivanhofer!

If I'm understanding this correctly, if someone is using vanilla JS (no explicit type annotations) but still relying on the type declarations for IDE feedback, they will always be able to use any argument arity and types in event invocations. When using TypeScript, if the action method signatures are explicitly defined, you will only be able to use the specified arity / types. Correct?

Assuming that's correct – I think this approach makes sense. Given the dynamic nature of JS and svelte-ism, and the way args can be forwarded to lifecycle events, it makes sense that the type validation would be less strict (allow for all possible argument passing scenarios) if the user has not explicitly defined the allowed args.

**Comment by kenkunz** [comment]
After reviewing the code and tests, I believe there may be another small bug in the type defs.

An action method can return a `string`, `symbol` or `undefined` – e.g.,
```javascript
const machine = fsm('foo', {
  foo: {
    returnsString() { return 'bar'; },
    returnsSymbol() { return Symbol.for('bar'); }
    returnsUndefined() {}
  }
});
```

…but the _event invocations_ always return a `string` or `symbol` – because the event invocations return the _current state_ (after any transitions resulting from the invocation), which can only be a `string` or `symbol`. So the below event invocations would return the values shown in the comments (assuming they are _not_ invoked sequentially … just a single invocation after initializing `machine`):
```javascript
machine.returnsString()    // => 'bar' (action caused a transition to 'bar')
machine.returnsSymbol()    // => Symbol.for('bar') (action caused a transition to Symbol.for('bar') )
machine.returnsUndefined() // => 'foo' (action returned undefined, so there was no transition)
```

Looking at our [current type tests](https://github.com/ivanhofer/svelte-fsm/blob/15164e03628044840f8407f0a24f75306e87ea26/test/types.ts#L98) – it appears our type defs expect a `void` return value when the action returns `undefined`.

Sorry… I should have caught this in the previous PR. Hoping this is relatively straightforward to fix 🤞?

**Comment by ivanhofer** [comment]
@kenkunz `returnsUndefined() {}` would be typed as `void`. You would need to write `returnsReallyUndefined() { return undefined }` to make the call signature return `undefined`
`

**Comment by kenkunz** [comment]
@ivanhofer your changes in 18fdc8f5da6327eb14796d3cd5b0f60b8cabe99e look good – I'm going to merge this and close the PR & issue.

Thanks again! Hopefully we won't see any other issues. I don't expect to make any API changes for a while – I'd like to see how this is used in the wild for a bit / what type of enhancement requests come in.

**Comment by ivanhofer** [comment]
@kenkunz and I didn't know it behaves like tis in JavaScript 😅
I exclusively use TypeScript since 2+ years now, so I might have forgotten how normal JavaScript behaves in certain situations.
Thanks for posting the link to StackOverflow 👍

**Pull request merged**
